// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int trials = Integer.parseInt(args[0]);

		int countLessOrEqualTo0_5 = 0;
		int countGreaterThan0_5 = 0;

		int i = 0;
		while (i < trials) {
			double randValue = Math.random();
			if (randValue <= 0.5) {
				countLessOrEqualTo0_5++;
			} else {
				countGreaterThan0_5++;
			}
			i++;
		}

		System.out.println("> 0.5: " + countGreaterThan0_5);
		System.out.println("<= 0.5: " + countLessOrEqualTo0_5);
		if (countLessOrEqualTo0_5 > 0) {
			System.out.println("Ratio: " + ((double) countGreaterThan0_5 / countLessOrEqualTo0_5));
		}
	}
}
